// <auto-generated />
namespace InventoryDC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SP_UserValidation_Select : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SP_UserValidation_Select));
        
        string IMigrationMetadata.Id
        {
            get { return "201711281427485_SP_UserValidation_Select"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
