// <auto-generated />
namespace InventoryDC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SP_Clients_get_enable_clients : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SP_Clients_get_enable_clients));
        
        string IMigrationMetadata.Id
        {
            get { return "201801041622141_SP_Clients_get_enable_clients"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
