// <auto-generated />
namespace InventoryDC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SP_Product_Get_Status_True : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SP_Product_Get_Status_True));
        
        string IMigrationMetadata.Id
        {
            get { return "201801041722554_SP_Product_Get_Status_True"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
