// <auto-generated />
namespace InventoryDC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SP_Invoice_Select_Last_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SP_Invoice_Select_Last_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201801042103331_SP_Invoice_Select_Last_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
